services:
  task-management:
    build: ./
    mem_limit: 512m
    ports:
      - "8080:8080"
    networks:
      - app-postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres
    image: postgres:16
    mem_limit: 512m
    networks:
      - app-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=task-management
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 2s
      retries: 60

networks:
  app-postgres:
    name: app-postgres